Repository googleinterns/step240-2020, pull requests merged in 2020-09, with the labels that each got.

#89 Fix master compilation failure
  src/main/java/com/google/graphgeckos/dashboard/DashboardApplication.java
  src/main/java/com/google/graphgeckos/dashboard/fetchers/github/GitHubController.java
  src/main/java/com/google/graphgeckos/dashboard/fetchers/github/GitHubData.java
  src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
  src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
Labels: P0

#80 Fetch Data from Endpoint as BuildSnapshotContainer Mounts
  src/main/webapp/components/BuildSnapshotContainer.js
Labels: P0

#122 Update Maven Toolchain to Deploy Application
  .gitignore
  pom.xml
  src/main/webapp/package-lock.json
Labels: P0

#102 Replace App Wrapper with React Fragment
  src/main/webapp/App.js
Labels: P0

#125 Pass Navigation Options to Navigation Component Instance
  src/main/webapp/components/Header.js
  src/main/webapp/components/Navigation.js
Labels: P0

#112 Update BuildInfo to work with DatastoreTemplate
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildInfo.java
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuilderStatus.java
Labels: P0

#111 Simplify BuilderStatus
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuilderStatus.java
Labels: P0

#110 Update BuildBotData to work with DatastoreTemplate
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildBotData.java
Labels: P0

#143 Fix master compilation failure
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildBotData.java
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuilderStatus.java
  src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
  src/main/webapp/package-lock.json
  src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
Labels: P0

#126 Rename Prop to Match Expected Name
  src/main/webapp/components/BuildSnapshotContainer.js
Labels: P1

#132 Style Header Component
  src/main/webapp/style.css
Labels: P1

#145 Add equals method to BuildBotData
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildBotData.java
Labels: P0

#140 Use getField to Fetch Props
  src/main/webapp/components/BuilderDataTable.js
  src/main/webapp/components/Navigation.js
Labels: P1

#128 Include BuilderDataTable and Incoming BuilderGrid
  src/main/webapp/components/BuildSnapshot.js
Labels: P1

#130 Implement Structure for BuilderGrid Component
  src/main/webapp/components/BuilderGrid.js
Labels: P1

#157 Catch GET Request errors and Change Target Endpoint
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/package-lock.json
Labels: P0

#159 Resolve res.json() Before Setting Data
  src/main/webapp/components/BuildSnapshotContainer.js
Labels: P0

#162 Add Missing Parameters to Fetch
  src/main/webapp/components/BuildSnapshotContainer.js
Labels: P0

#164 Replace mvn deploy command with gcloud deploy in deploy.sh
  deploy.sh
Labels: P0

#167 Include missing import from BuilderDataTable
  src/main/webapp/components/BuilderDataTable.js
Labels: P0

#165 Style BuildSnapshot Container
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/style.css
Labels: P1

#160 Refactor Navigation Structure & Styling
  src/main/webapp/components/Header.js
  src/main/webapp/style.css
Labels: P0

#137 Style Body and Add Colours for Theme
  src/main/webapp/style.css
Labels: P1

#173 BuildBot fetcher implementation
  pom.xml
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildBotData.java
  src/main/java/com/google/graphgeckos/dashboard/fetchers/buildbot/BuildBotClient.java
  src/test/java/com/google/graphgeckos/dashboard/buildbot/BuildBotClientTest.java
  src/test/java/com/google/graphgeckos/dashboard/buildbot/BuildBotClientTestInfo.java
  src/test/resources/jsons/buildbots/input_clang-x86_64-debian-fast.txt
  src/test/resources/jsons/buildbots/input_fuchsia-x86_64-linux.txt
  src/test/resources/jsons/buildbots/output_clang-x86_64-debian-fast.txt
  src/test/resources/jsons/buildbots/output_fuchsia-x86_64-linux.txt
Labels: P0

#177 Add User Feedback for Results of Fetch
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/style.css
Labels: P2

#172 Style Top Row of Tray
  src/main/webapp/style.css
Labels: P1

#171 Style Builder Grid
  src/main/webapp/style.css
Labels: P1

#168 Refactor Header Style and Move Border Rule to Wrapper
  src/main/webapp/style.css
Labels: P1

#176 Deprecate getField & getFields
  src/main/webapp/components/BuildSnapshot.js
  src/main/webapp/components/BuilderDataTable.js
  src/main/webapp/components/BuilderGrid.js
  src/main/webapp/components/Navigation.js
  src/main/webapp/components/utils/getField.js
  src/main/webapp/components/utils/getFields.js
Labels: P0

#182 Safely Open Navigation Links in New Tab
  src/main/webapp/components/Navigation.js
Labels: P2

#187 Add Licensing Blurb to files (JS & CSS)
  src/main/webapp/App.js
  src/main/webapp/components/BuildSnapshot.js
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/components/BuilderDataTable.js
  src/main/webapp/components/BuilderGrid.js
  src/main/webapp/components/Header.js
  src/main/webapp/components/Navigation.js
  src/main/webapp/index.js
  src/main/webapp/style.css
Labels: P2

#178 Integrate GitHub fetcher with the storage
  src/main/java/com/google/graphgeckos/dashboard/fetchers/github/GitHubController.java
  src/test/java/com/google/graphgeckos/dashboard/github/GitHubControllerTests.java
  src/test/java/com/google/graphgeckos/dashboard/github/GitHubJsonTestInfo.java
Labels: P0

#123 Create BuilderIndex class to store inside Datastore
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuilderIndex.java
Labels: P1

#124 Implementation of Index set and retrieval operations on DatastoreRepository
  src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
  src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
Labels: P1

#194 Maven dependency fix
  pom.xml
  src/test/java/com/google/graphgeckos/dashboard/buildbot/BuildBotClientTest.java
Labels: P0

#190 Update Prop Name to Align with Prop Expected by BuilderGrid
  src/main/webapp/components/BuildSnapshot.js
Labels: P0

#191 Add Key to Components Generated with Array.map
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/components/BuilderDataTable.js
Labels: P1

#174 Style BuilderDataTable
  src/main/webapp/style.css
Labels: P1

#189 Refactor Destructuring
  src/main/webapp/components/BuildSnapshot.js
Labels: P0

#121 Update DataRepository interface to support buildbot indices
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuilderIndex.java
  src/main/java/com/google/graphgeckos/dashboard/storage/DataRepository.java
  src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
  src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
Labels: P1

#175 Change BuildSnapshot Styling with onclick event
  src/main/webapp/components/BuildSnapshot.js
  src/main/webapp/style.css
Labels: P1

#198 Fix Header Styling
  src/main/webapp/components/BuildSnapshot.js
  src/main/webapp/style.css
Labels: P0

#205 Failing DashboarController test fix
  src/test/java/com/google/graphgeckos/dashboard/api/DashboardControllerTest.java
Labels: P0

#193 Add styling for pagination
  src/main/webapp/style.css
Labels: P1

#197 Add Missing Key to Table and Stretch to fill Tray
  src/main/webapp/components/BuilderDataTable.js
  src/main/webapp/style.css
Labels: P1

#211 Pad BuildSnapshotContainer
  src/main/webapp/style.css
Labels: P3, enhancement

#188 Remove props parameter where props are not expected
  src/main/webapp/components/BuildSnapshotContainer.js
  src/main/webapp/components/Header.js
  src/main/webapp/index.js
Labels: P3, enhancement

#196 Adjust Snapshot Background based on Build Status
  src/main/webapp/components/BuildSnapshot.js
  src/main/webapp/style.css
Labels: P1

#213 Catch undefined error when accessing builder array
  src/main/webapp/components/BuildSnapshot.js
Labels: P0, bug

#215 add global revision status
  src/main/java/com/google/graphgeckos/dashboard/datatypes/BuildInfo.java
  src/main/java/com/google/graphgeckos/dashboard/datatypes/RevisionStatus.java
  src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
  src/test/java/com/google/graphgeckos/dashboard/datatypes/BuildInfoTests.java
Labels: P0

#217 Catch undefined error when accessing build steps
  src/main/webapp/components/BuildSnapshot.js
Labels: P0, bug

#192 Add pagination functionality
  src/main/webapp/components/BuildSnapshotContainer.js
Labels: P1

#218 Fix error due to timestamp format mismatch
  src/main/webapp/components/BuildSnapshot.js
Labels: P0, bug

#204 Add a config file with initial build bot data
  src/main/java/com/google/graphgeckos/dashboard/DashboardApplication.java
  src/main/java/com/google/graphgeckos/dashboard/reader/BuildBotSetUpData.java
  src/main/java/com/google/graphgeckos/dashboard/reader/BuildBotSetUpReader.java
  src/main/resources/static/buildbots.txt
  src/test/java/com/google/graphgeckos/dashboard/reader/BuildBotSetUpReaderTest.java
  src/test/resources/jsons/reader/input_just_json.txt
Labels: P0

#219 Scope variable properly
  src/main/webapp/components/BuildSnapshot.js
Labels: bug

#212 Add boilerplate license to DashboardController
  src/main/java/com/google/graphgeckos/dashboard/api/DashboardController.java
Labels: P0, documentation
